---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
permission_kind: "{{ _ansible_tower_com_permission.kind }}"
permission_metadata_namespace: "{{ _ansible_tower_com_permission.metadata.namespace }}"
permission_metadata_name: "{{ _ansible_tower_com_permission.metadata.namespace }}"
permission_api_version: "{{ _ansible_tower_com_permission.api_version }}"
# Merge CR spec with finalize_config dictionary from watches.yaml
permission_spec: "{{ _ansible_tower_com_permission_spec | combine(finalize_config|default({})) }}"
permission_spec_name: "{{ permission_spec.name }}"
permission_spec_secret: "{{ permission_spec.secret }}"
permission_spec_collection: "{{ permission_spec.collection }}"
permission_spec_config: "{{ permission_spec.config }}"
