---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
project_kind: "{{ _ansible_tower_com_project.kind }}"
project_metadata_namespace: "{{ _ansible_tower_com_project.metadata.namespace }}"
project_metadata_name: "{{ _ansible_tower_com_project.metadata.namespace }}"
project_api_version: "{{ _ansible_tower_com_project.api_version }}"
# Merge CR spec with finalize_config dictionary from watches.yaml
project_spec: "{{ _ansible_tower_com_project_spec | combine(finalize_config|default({})) }}"
project_spec_name: "{{ project_spec.name }}"
project_spec_secret: "{{ project_spec.secret }}"
project_spec_collection: "{{ project_spec.collection }}"
project_spec_config: "{{ project_spec.config }}"
