---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
inventory_kind: "{{ _ansible_tower_com_inventory.kind }}"
inventory_metadata_namespace: "{{ _ansible_tower_com_inventory.metadata.namespace }}"
inventory_metadata_name: "{{ _ansible_tower_com_inventory.metadata.namespace }}"
inventory_api_version: "{{ _ansible_tower_com_inventory.api_version }}"
# Merge CR spec with finalize_config dictionary from watches.yaml
inventory_spec: "{{ _ansible_tower_com_inventory_spec | combine(finalize|default({})) }}"
inventory_spec_name: "{{ inventory_spec.name }}"
inventory_spec_secret: "{{ inventory_spec.secret }}"
inventory_spec_collection: "{{ inventory_spec.collection }}"
inventory_spec_config: "{{ inventory_spec.config }}"
