---
- name: "Assert variables"
  assert:
    that:
      - credential_api_version is defined
      - credential_api_version is string
      - credential_kind is defined
      - credential_kind is string
      - credential_spec_collection is defined
      - credential_spec_collection is in ['awx.awx', 'ansible.tower']
      - credential_spec_name is defined
      - credential_spec_name is string
      - credential_spec_config is defined
      - credential_spec_config is mapping
      - credential_spec_vars is defined
      - credential_spec_vars is mapping

- name: "credential: Calling desired state specific tasks"
  include_tasks: "{{ _credential_spec_config_state }}"
  vars:
    # yamllint disable-line rule:line-length
    _credential_spec_config_state: "{{ credential_spec_config.state | default('present') }}"
