---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
credential_kind: "{{ _ansible_tower_com_credential.kind }}"
credential_metadata_namespace: "{{ _ansible_tower_com_credential.metadata.namespace }}"
credential_metadata_name: "{{ _ansible_tower_com_credential.metadata.namespace }}"
credential_api_version: "{{ _ansible_tower_com_credential.api_version }}"
# Merge CR spec with finalize_config dictionary from watches.yaml
credential_spec: "{{ _ansible_tower_com_credential_spec | combine(finalize|default({})) }}"
credential_spec_name: "{{ credential_spec.name }}"
credential_spec_secret: "{{ credential_spec.secret }}"
credential_spec_collection: "{{ credential_spec.collection }}"
credential_spec_config: "{{ credential_spec.config }}"
