---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: permissions.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: Permissions
    listKind: PermissionList
    plural: permissions
    singular: permission
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Schema validation for the Tower Permission CRD.
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            secret:
              type: string
            collection:
              type: string
              enum:
                - "awx.awx"
                - "ansible.tower"
              default: "awx.awx"
              description: |
                Module's collection.
            config:
              description: |
                List of parameters of each module:
                 https://docs.ansible.com/ansible/latest/collections/awx/awx/index.html#modules
              type: object
              x-kubernetes-preserve-unknown-fields: true
          required:
          - secret
          - config
          type: object
      type: object
      x-kubernetes-preserve-unknown-fields: true
