---
apiVersion: tower.ansible.com/v1alpha1
kind: Credential
metadata:
  name: "scm-credential:example-github.com"
  namespace: awx
spec:
  secret: toweraccess
  vars:
    ## Query Secret CR in kubernetes and associate
    ## its value to variable `k8s_secret_data`
    ## This process ensure that when Secret CR is updated,
    ## these values will cascade to Tower during reconcile.
    k8s_secret_data: "{{ 
      lookup(
        'community.kubernetes.k8s',
        kind='Secret',
        namespace='awx',
        resource_name='credential:example-github.com'
      )[0]['data']
    }}"
  config:
    ## Variable created by operator-sdk for ansible.
    ##   _<group_as_snake>_<kind>: {
    ##       <cr_object> as is
    ##   }
    name: "{{ _ansible_tower_com_credential.metadata.name }}"
    organization: Default
    credential_type: "Source Control"
    inputs:
      ## Secrets data are encoded in base64.
      ## We need to decode it before defining its value in Tower.
      username: "{{ k8s_secret_data.username | base64decode }}"
      password: "{{ k8s_secret_data.password | base64decode }}"
      ssh_key_data: "{{ k8s_secret_data.ssh_private_key | base64decode }}"
      ssh_key_unlock: "{{ k8s_secret_data.ssh_unlock_key | base64decode }}"
