apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: examplejobtemplate
  namespace: awx
spec:
  secret: toweraccess
  config:
    name: ExampleJobTemplate
    project: Demo Project
    playbook: hello_world.yml
    inventory: Demo Inventory
