---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
job_template_kind: "{{ _ansible_tower_com_job_template.kind }}"
# yamllint disable-line rule:line-length
job_template_metadata_namespace: "{{ _ansible_tower_com_job_template.metadata.namespace }}"
# yamllint disable-line rule:line-length
job_template_metadata_name: "{{ _ansible_tower_com_job_template.metadata.namespace }}"
job_template_api_version: "{{ _ansible_tower_com_job_template.api_version }}"
# Merge CR spec with finalize_config dictionary from watches.yaml
# yamllint disable-line rule:line-length
job_template_spec: "{{ _ansible_tower_com_job_template_spec | combine(finalize|default({})) }}"
job_template_spec_name: "{{ job_template_spec.name }}"
job_template_spec_secret: "{{ job_template_spec.secret }}"
job_template_spec_collection: "{{ job_template_spec.collection }}"
job_template_spec_config: "{{ job_template_spec.config }}"
