---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
organization_kind: "{{ _ansible_tower_com_organization.kind }}"
organization_metadata_namespace: "{{ _ansible_tower_com_organization.metadata.namespace }}"
organization_metadata_name: "{{ _ansible_tower_com_organization.metadata.namespace }}"
organization_api_version: "{{ _ansible_tower_com_organization.api_version }}"
# Merge CR spec with finalize_config dictionary from watches.yaml
organization_spec: "{{ _ansible_tower_com_organization_spec | combine(finalize|default({})) }}"
organization_spec_name: "{{ organization_spec.name }}"
organization_spec_secret: "{{ organization_spec.secret }}"
organization_spec_collection: "{{ organization_spec.collection }}"
organization_spec_config: "{{ organization_spec.config }}"
