---
- name: Create team
  include_role:
    name: "module"
  vars:
    module_kind: "{{ team_spec }}"
    module_metadata_namespace: "{{ team_spec }}"
    module_metadata_name: "{{ team_spec }}"
    module_api_version: "{{ team_spec }}"
    module_spec: "{{ team_spec }}"
    module_spec_name: "tower_team"
    module_spec_secret: "{{ team_spec.secret }}"
    module_spec_collection: "{{ team_spec.collection }}"
    module_spec_parameters: "{{ team_spec.config }}"
