---
## TODO: Tasks to Delete dependent objects
- name: Finalize permission
  include_role:
    name: "module"
  vars:
    module_kind: "{{ permission_spec }}"
    module_metadata_namespace: "{{ permission_spec }}"
    module_metadata_name: "{{ permission_spec }}"
    module_api_version: "{{ permission_spec }}"
    module_spec: "{{ permission_spec }}"
    module_spec_name: "tower_role"
    module_spec_secret: "{{ permission_spec.secret }}"
    module_spec_collection: "{{ permission_spec.collection }}"
    module_spec_parameters: "{{ permission_spec.config }}"
