---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
user_kind: "{{ _ansible_tower_com_user.kind }}"
user_metadata_namespace: "{{ _ansible_tower_com_user.metadata.namespace }}"
user_metadata_name: "{{ _ansible_tower_com_user.metadata.namespace }}"
user_api_version: "{{ _ansible_tower_com_user.api_version }}"
# Merge CR spec with finalize_config dictionary from watches.yaml
user_spec: "{{ _ansible_tower_com_user_spec | combine(finalize_config|default({})) }}"
user_spec_name: "{{ user_spec.name }}"
user_spec_secret: "{{ user_spec.secret }}"
user_spec_collection: "{{ user_spec.collection }}"
user_spec_config: "{{ user_spec.config }}"
